### ISSUE TITLE
项目跑不起来

### ISSUE THREAD

**Issue by KunMinX** [kira2015/flutter-skill-tree#1]
flutter、Dart SDK 安装的是最新的。
是我打开方式有问题吗？

![20190813003509.png](https://i.loli.net/2019/08/13/2c4KIyOamw5dnGB.png)

**Comment by asjqkkkk** [comment]
项目本身可以直接运行的，example目录下的是另外其他单独的项目，也可以单独运行

**Comment by KunMinX** [comment]
@asjqkkkk  
好的。
猜测是我遇到了不明状况。
flutter doctor 的结果显示，从 flutter 主页 clone 的 flutter SDK 版本是 0.0.0 unknown。
我在 flutter issues 中找到解决方案，并试着清除并重新 clone 了，结果仍如是。
请问有遇到过并且有可行的解决方案吗？

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.0.0-unknown, on Microsoft Windows [Version 10.0.17134.885], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.4)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio (version 3.5)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.37.0)
[√] Connected device (1 available)

! Doctor found issues in 2 categories.

**Comment by asjqkkkk** [comment]
@KunMinX 试一试 flutter channel dev 切换到dev分支

**Comment by asjqkkkk** [comment]
试一试下面这行代码切换到dev分支
`flutter channel dev`
然后
`flutter version`
打印出所有版本
选择其中某个版本,进行切换，比如
`flutter version v1.7.8+hotfix.4`

**Comment by KunMinX** [comment]
@asjqkkkk 本地似乎不存在 dev 通道，另外 version 查询结果为空行

D:\Projects\FlutterProjects\flutter\flutter>flutter channel
Flutter channels:
* master

D:\Projects\FlutterProjects\flutter\flutter>flutter channel dev
Switching to flutter channel 'dev'...
git: fatal: 'origin/dev' is not a commit and a branch 'dev' cannot be created from it
Switching channels failed with error code 128.

**Comment by kira2015** [comment]
应该本地环境没有搭好，你的Android studio都没有连接flutter SDK和Dart，来 https://www.yuque.com/sc0cqi/ys9h7c/ywfbln  ，一起flutter 走一波！

**Comment by asjqkkkk** [comment]
😂你的flutter环境什么的估计还没装好吧

**Comment by KunMinX** [comment]
@asjqkkkk  @kira2015  好的，我卸载重新试试。😂 打算在 vs 中上手 flutter

**Comment by KunMinX** [comment]
@asjqkkkk @kira2015 跑起来了 很棒！

**Comment by asjqkkkk** [comment]
@KunMinX 问题解决后，记得及时关闭issue哦。
如果你觉得这个项目不错或者对你有帮助的话，不妨给个star🌟🌟
😄

**Comment by KunMinX** [comment]
@asjqkkkk  no problem！
